### PR TITLE
added Dutch translation

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by indication** [comment]
Thank you for translation.
It will be released next.

**Comment by indication** [comment]
Uploaded to translation platform.
You can translate this via transifex.
https://www.transifex.com/openredmine
Thank you.

**Comment by PanderMusubi** [comment]
Got a 404...

**Comment by indication** [comment]
Oops, sorry that is for logged in users.
https://www.transifex.com/openredmine/openredmine/dashboard/

**Comment by PanderMusubi** [comment]
Done :)

**Pull request merged**
